require:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.1
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'script/**/*'
    - 'spec/rails_helper.rb'
    - 'vendor/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'spec/spec_helper.rb'
    - 'config.ru'

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'feature', 'scenario', 'let', 'it']

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: 'compact'